# Generated by Django 3.1.7 on 2021-02-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    #operations = [
     #   migrations.RenameField(
      #      model_name='students',
       #     old_name='studentid',
        #    new_name='id',
        #),
   # ]
